{% set name = "buildbot-grid-view" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4b5e411475e797875bdbdc5f397bd742363d55d01baf0db99d8f199fc3892d8

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >3.5
    - buildbot-pkg
  run:
    - python >3.5
    - buildbot-pkg
    - buildbot-www

test:
  imports:
    - buildbot_grid_view

about:
  home: https://buildbot.net/
  license: GNU General Public (GPL)
  license_family: LGPL
  license_file: LICENSE
  summary: Buildbot Grid View plugin
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
