{% set name = "buildbot-grid-view" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ecf0969720c10e2a075ea4540df06db31a515b31cf584f5548a501f29a98011

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
    - buildbot-pkg
  run:
    - python >3.5
    - buildbot-pkg
    - buildbot-www

test:
  imports:
    - buildbot_grid_view
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://buildbot.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Buildbot Grid View plugin
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
