travis:
  secure:
    BINSTAR_TOKEN: E70sIMVILx6x0txf/i8UIbIjoQAzZ+SVkV0XJbOYSz0m5d0vPxDiFBQW+9ZfoeRyjRQPB7AS+4FaMA2GX7NgJts0mRmhsJvJuTr2zK91EQ02pX7j0+f/4zoRwjHkQ/nHWThY7F+efqv2A9W04g2FESFihkT6XemEIscgAfbtvEnF3ARjOBoHqhcy81qRuOjA2aOYXYhJC7PQuKLH1V1FaLtKCjxonk+CBTN2ThpGg3TJ43M84szIZgeKgegVTSoL+il3xi0zxyhXdBQjTFJcCXFvOVmzetX6J7f0a2r4Q3eVPVdH8pOtWKh5rG3cWRggNMP2iBy2B38keYgmagcnIpodm0jjQ+sJFDTe1cOArKJYdNgqvqVl+GDw540+DSxqd7jtfvF+MGEEXGwniWQBxdt1YhqBn9m8SxiBwyUrxsAHVXGIYYzG0seVlr8aJY/tOloNPLyjXgygbD5pTClD5p+2/0dzLNxHu362jIWJkgKVpXOwcN5oecyzGHqUxGawlPBEBjwzTJwYywDfIhLEEC49mxeUYG0zU+m2Cun6EJJVEI1mkzssk9C9booKVivqIrdVo8StYq/SkyyDSQTgbd92IaCLJubEpAdZ/jqPyxR+4aNJKMt1Va0aa4lJ8ExiAi5maEmqB84RezymI/v/Cl6zFxnhl/Bc/8Yac+w7wbQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
